---
- name: Quiz Playbook
  hosts: pod-batutahid-managed2
  remote_user: student
  become: yes
  tasks:
    - name: Install latest packages
      apt:
        name:
          - apache2
          - mariadb-server
          - php
          - php-mysql
        state: latest

    - name: Ensure the apache2 and mariadb services are enabled and running
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mariadb

    - name: copy the text Adinusa quiz Playbook - batutahid
      copy:
        content: "Adinusa quiz Playbook - batutahid"
        dest: /var/www/html/index.php


- name: Quiz Playbook
  hosts: localhost
  tasks:
    - name:  tests the web service running
      uri: 
        url: http://pod-batutahid-managed2/index.php
      register: result

    - debug:
        var: result.content
