---
- hosts: managed1-host-batutahid
  become: yes
  vars_files: secret.yml
  tasks:
    - name: Create user based on group_vars
      user:
        name: "{{ item }}"
        password: "{{ pass | password_hash('sha512') }}"
      loop: "{{ list_user_ops_managed1 }}"
      when: inventory_hostname == 'pod-batutahid-managed1'

    - name: Create user based on group_vars
      user:
        name: "{{ item }}"
        password: "{{ pass | password_hash('sha512') }}"
      loop: "{{ list_user_dev_managed1 }}"
      when: inventory_hostname == 'pod-batutahid-managed1'

- hosts: managed2-host-batutahid
  become: yes
  vars_files: secret.yml
  tasks:
    - name: Create user based on group_vars
      user:
        name: "{{ item }}"
        password: "{{ pass | password_hash('sha512') }}"
      loop: "{{ list_user_ops_managed2 }}"
      when: inventory_hostname == 'pod-batutahid-managed2'

    - name: Create user based on group_vars
      user:
        name: "{{ item }}"
        password: "{{ pass | password_hash('sha512') }}"
      loop: "{{ list_user_dev_managed2 }}"
      when: inventory_hostname == 'pod-batutahid-managed2'
