---
- hosts: all
  become: yes
  tasks:
    - name: Import mariadb gpg
      shell: curl -fsSL http://mirror.mariadb.org/PublicKey_v2 | sudo gpg --dearmor | sudo tee /usr/share/keyrings/mariadb.gpg > /dev/null

    - name: Copy mariadb repository
      template:
        src: templates/mariadb.list.j2
        dest: /etc/apt/sources.list.d/mariadb.list
        owner: root
        group: root

    - name: Copy nginx repository
      template:
        src: templates/nginx.list.j2
        dest: /etc/apt/sources.list.d/nginx.list
        owner: root
        group: root

    - name: Update repository
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - nginx
          - mariadb-server
          - mariadb-client
        state: present

    - name: Ensure servis is started and enabled
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - mariadb
