---
# tasks file for quiz-roles
- name: Install apache2
  apt:
    name: apache2
    state: latest

- name: Start end enable apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Copy config file
  template:
    src: quiz-roles.conf.j2
    dest: /etc/apache2/sites-available/quiz-roles.conf

- name: enable webserver configuration
  command: a2ensite quiz-roles.conf
  notify: restart apache2

- name: Ensure webroot is present
  file:
    path: /var/www/quiz-roles/{{ ansible_hostname }}
    state: directory

- name: Copy index.html
  copy:
    src: html-quiz/index.html
    dest: /var/www/quiz-roles/{{ ansible_hostname }}/index.html


